### ISSUE TITLE
Firebase.Ref(pagth): concurrent map iteration and map write 

### ISSUE THREAD

**Issue by gabriel** [zabawaba99/firego#92]
I think I called Ref very fast in succession?

```go
fatal error: concurrent map iteration and map write

goroutine 173 [running]:
runtime.throw(0x451fc4e, 0x26)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/panic.go:605 +0x95 fp=0xc42004f1b8 sp=0xc42004f198 pc=0x402c435
runtime.mapiternext(0xc42004f308)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/hashmap.go:778 +0x6f1 fp=0xc42004f250 sp=0xc42004f1b8 pc=0x400bba1
runtime.mapiterinit(0x44c2f80, 0xc42016a120, 0xc42004f308)
	/usr/local/Cellar/go/1.9.4/libexec/src/runtime/hashmap.go:768 +0x270 fp=0xc42004f2b8 sp=0xc42004f250 pc=0x400b250
github.com/zabawaba99/firego.(*Firebase).copy(0xc420064300, 0x0)
	/Users/gabe/go/src/github.com/zabawaba99/firego/firebase.go:217 +0x1c5 fp=0xc42004f378 sp=0xc42004f2b8 pc=0x43c3875
github.com/zabawaba99/firego.(*Firebase).Ref(0xc420064300, 0xc420018180, 0x30, 0x1, 0x1, 0xc420018180)
	/Users/gabe/go/src/github.com/zabawaba99/firego/firebase.go:109 +0x35 fp=0xc42004f400 sp=0xc42004f378 pc=0x43c29f5
```

**Comment by zabawaba99** [comment]
Hey @gabriel , let me see if I can take a look at this in the next couple of days

**Comment by zabawaba99** [comment]
Hey @gabriel , sorry it took so long to address this. There should be a fix for this in the v1 branch now. Please let me know if you still see this behavior.
